### ISSUE TITLE
Code do not compile

### ISSUE THREAD

**Issue by electroZ-microsystems** [AprilBrother/esp-soil-moisture-sensor#2]
Compilation (Arduino 1.6.12) problem in line 8: 
`const int PIN_CLK   = D5;`
Error  ->  'D5' was not declared in this scope

No clear if D5 means GPIO5 !?

If I see the electronic diagram I would write that:
```
const int PIN_CLK   = 14; //D5;
const int PIN_SOIL  = A0; 
const int PIN_LED   = 13; //D7;
const int PIN_SWITCH = 12; // D8;
```

But not sure.

**Comment by volca** [comment]
Did you install ESP8266 package for Arduino IDE first? Please check [our wiki](http://wiki.aprbrother.com/wiki/ESP_Soil_Moisture_Sensor_Using_Arduino_IDE#Install_the_Arduino_IDE_1.6.8) to install package first.

You should also choose right board type "NodeMCU 1.0".

Let me know if this work.

**Comment by electroZ-microsystems** [comment]
Hello,  

Yes it works like that. Thanks you for your fast answere. May be you should add this information in the code and in the documentation.  

Emmanuel  

Did you install ESP8266 package for Arduino IDE first? Please check our wiki to install package first.

```
You should also choose right board type "NodeMCU 1.0".

Let me know if this work.

�
```

**Comment by volca** [comment]
Thank you for your confirming. I added a link for [quick start](http://wiki.aprbrother.com/wiki/ESP_Soil_Moisture_Sensor#Quick_Start).
