### ISSUE TITLE
Board design

### ISSUE THREAD

**Issue by dannybloe** [AprilBrother/esp-soil-moisture-sensor#3]
Howdee, 

Great project! Do you also have the board design or somewhere where I can get the pcbs?

Cheers!

Danny

**Comment by volca** [comment]
I will send the PCB file to your email

**Comment by dannybloe** [comment]
Great! Looking forward to it. You can see my email in my account info on github.

**Comment by palka82** [comment]
> I will send the PCB file to your email
Hi!
can I send it?

**Comment by palka82** [comment]
> I will send the PCB file to your email

H! can I send it?
