### ISSUE TITLE
Hardware for v2.2

### ISSUE THREAD

**Issue by MoJo2600** [AprilBrother/esp-soil-moisture-sensor#4]
Hi,

would you share the schematics and maybe some example code for rev 2.2 of your board?

Regards

Christian

**Comment by volca** [comment]
The schematci for v2.2 is same with v2.1. Please check [the link](https://github.com/AprilBrother/esp-soil-moisture-sensor/tree/master/hardware/2.1) .

You can also find source code [here](https://github.com/AprilBrother/esp-soil-moisture-sensor/tree/master/src/esp-soil-moisture-sensor-v2.1)

**Comment by MoJo2600** [comment]
Thank you for clarifying!

Best regards

Christian
