### ISSUE TITLE
Is there mqtt support?

### ISSUE THREAD

**Issue by cputoaster** [AprilBrother/esp-soil-moisture-sensor#5]

**Comment by volca** [comment]
Yes. ESP8266 has some great MQTT libraries. You can modify our exists code with the [pubsubclient](https://github.com/Imroy/pubsubclient) library.

I used this library with other ESP8266 project and it works fine.

**Comment by MoJo2600** [comment]
I will try to flash homie https://github.com/marvinroger/homie-esp8266 on the device. I can share my code when it works. I have it running on a few temperature sensors.

**Comment by cputoaster** [comment]
I guess I will start with ordering one :-). And then I somehow have to make it outdoor capable.

**Comment by volca** [comment]
@MoJo2600  Wait for your good news!

@cputoaster Don't forget to buy one ESP Flasher Rev4 to programing the sensor easier

**Comment by cputoaster** [comment]
Yes, I already programmed lots of Sonoff devices, I guess I can use the same flasher, no? (Mini USB UART FTDI Programmer 3.3/5V USB Serial)

**Comment by volca** [comment]
@cputoaster  Yes. you can use that flasher directly.

**Comment by volca** [comment]
I closed the issue.

**Comment by MoJo2600** [comment]
It took a long time, but I'm in the progress of finishing my MQTT code for the soil moisture sensor. Currently I'm testing if everything is working properly but two of my sensors are sending values. You can find my code here: https://github.com/MoJo2600/esp-soil-moisture-sensor
