### ISSUE TITLE
Not working with espeasy

### ISSUE THREAD

**Issue by manolo75** [AprilBrother/esp-soil-moisture-sensor#8]
Hi,

I would like to use that device with espeasy but it is not working.

**Comment by volca** [comment]
Could you please describe "it is not working" with espeasy?

**Comment by manolo75** [comment]
I can flash it with espeasy and run it, but I can not get any value for temperature and soil moisture.

**Comment by volca** [comment]
I think default espeasy firmware can't compatible with the sensor. please check [our source code](https://github.com/AprilBrother/esp-soil-moisture-sensor/tree/master/src/esp-soil-moisture-sensor-v2.1) instead

**Comment by manolo75** [comment]
The thing is I don't want to use an external MQTT like thingspeak, but I have my own on my raspberry with Mosquitto + domoticz.

Espeasy is perfect for that.

**Comment by volca** [comment]
please check [the link](https://bbs.aprbrother.com/t/april-brother-soil-moisture-crahes-on-esp-deepsleep-function/1698/9). Is it helpful?

**Comment by manolo75** [comment]
Yes it is a start, but I guess more devices will be sold after there is a plugin for espeasy like this one working :
https://espeasy.readthedocs.io/en/latest/Plugin/P047.html

I have successfully programmed my device with Arduino IDE. Changed the parameters. It is connecting to my wifi, but nothing is updated in domoticz. Trying to figuring out why.

**Comment by manolo75** [comment]
Ok it works now, I had to add the correct MQTT server in domoticz. For some reasons I ignore, the device updates domoticz once, but never refresh. I tried to change the value for SLEEP_TIME to 600000000, but still no refresh.

**Comment by manolo75** [comment]
I guess the software is crashing because it never wakes up.

**Comment by volca** [comment]
Did you wire the jumper for GPIO16? It’s designed for deepsleep. The jumper wires GPIO16 to reset pin.

**Comment by manolo75** [comment]
No, I ignored that. I don't have any jumper, I will try to figure out what I can do.

**Comment by manolo75** [comment]
Ok you were right, it is much better. Thanks.

**Comment by volca** [comment]
Thanks for update. 

We're also [testing new soil moisture sensor with ESP32 S2](https://twitter.com/linlinqi/status/1328982376270053376). Are you interested in the new one? I can ship one free sample to you.

I [migrated codes to the sensor also](https://github.com/volca/esp-soil)

**Comment by volca** [comment]
But the Arduino core for ESP32 S2 is not stable. It missed some important functions.

**Comment by manolo75** [comment]
Sure!  That is great news.

Let me know how to proceed.

Thank you. Regards

Manu

**Comment by volca** [comment]
please send a private message to [my twitter](https://twitter.com/linlinqi) about your previous order number. We'll use the shipping address to ship the new sample.

I will close the issue right now

**Comment by manolo75** [comment]
You can't be messaged on twitter ( linlinqi)

**Comment by volca** [comment]
I just open the option for direct message at twitter. See my private message

**Comment by manolo75** [comment]
Hi,

I just received the new beta sensor, thanks a lot.

I could not figure out how to assembly it since there is no hole to let the
board come through.

How do we do for the battery too?

Thanks.

Regards

Manu
